version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dcberr
      POSTGRES_PASSWORD: dcberr
      POSTGRES_DB: livestream-kahoot
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'

volumes:
  pgdata:
